{{- if and .Values.features.pv.enabled .Values.storage.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv-%s" (default "training" .Values.global.baseName) .Values.global.scenario | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.storage.size | default "10Gi" }}
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: {{ .Values.storage.reclaimPolicy | default "Delete" }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  hostPath:
    path: {{ .Values.storage.hostPath }}
{{- end }}
