{{- if and .Values.features.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ default "default-scenario" .Values.global.scenario | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  host: {{ required "app.host 必須設定（values.app.host）" .Values.app.host }}
  to:
    kind: Service
    name: {{ default "default-scenario" .Values.global.scenario | trunc 63 | trimSuffix "-" }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.app.tls.termination }}
  tls:
    termination: {{ .Values.app.tls.termination }}
    {{- if eq .Values.app.tls.termination "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.app.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
    {{- end }}
  {{- end }}
{{- end }}