{{- if .Values.features.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" (default "training" .Values.global.baseName) .Values.global.scenario | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
