apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-service
  namespace: up0123-test
spec:
  to:
    kind: Service
    name: demo-service
  port:
    targetPort: http
  tls:
    termination: edge