apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: up0123-test
spec:
  selector:
    app: demo-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
